camunda-community-hub/camunda-7-to-8-migration

backend-diagram-converter/core/src/main/java/org/camunda/community/converter/BpmnDiagramCheckResult.java, backend-diagram-converter/core/src/main/java/org/camunda/community/converter/MessageAppender.java
Currently, messages are appended to the result as they arrive from the visitors.
This can lead to bad information presentation, especially when multiple messages with different severities exist for each process element.
This enhancement sorts the messages by decreasing severity.
Presentation of the messages gets improved.
There is no direct testing as this fix completely relies on java- or jdk-native methods.
=> Messages are sorted by ordinal of severity

backend-diagram-converter/cli/README.md, backend-diagram-converter/cli/src/main/java/org/camunda/community/converter/cli/ConvertCommand.java, backend-diagram-converter/cli/src/test/java/org/camunda/community/converter/cli/ConvertCommandTest.java, backend-diagram-converter/cli/src/test/resources/c7.bpmn20.xml
As of now, only files with `.bpmn` ending were recognized as BPMN Files.
In fact, there was a time when BPMN Files had a `.bpmn20.xml` ending. 
We must not ignore this.
Closes #74 
There was a test added to check whether the ending would be recognized
=> Feature: Converter CLI now supports Legacy file ending

backend-diagram-converter/webapp/README.md, backend-diagram-converter/webapp/pom.xml, backend-diagram-converter/webapp/src/main/java/org/camunda/community/converter/webapp/ConverterController.java, backend-diagram-converter/webapp/src/main/java/org/camunda/community/converter/webapp/CsvWriterService.java, backend-diagram-converter/webapp/src/main/resources/static/index.html, backend-diagram-converter/webapp/src/test/java/org/camunda/community/converter/webapp/ConverterControllerTest.java, backend-diagram-converter/webapp/src/test/java/org/camunda/community/converter/webapp/CsvWriterServiceTest.java, backend-diagram-converter/webapp/src/test/resources/example.bpmn, pom.xml
Currently, the check result is returned as json by the API and displayed in the webapp.
This might not be useful for creating assets to structure a migration project.
For simplicity, a CSV export containing all data from the check result should be sufficient.
Closes #58 
There is a test for the `CsvWriterService` in place as well as for the RestController
=> Feature: Converter webapp exports Check results as CSV

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnConverter.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnDiagramCheckContext.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnDiagramCheckResult.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/ConversionElementAppender.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/DomElementVisitorContext.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractAttributeVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractBpmnAttributeVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractCamundaAttributeVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractCurrentlyNotSupportedAttributeVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractEventRefVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractRemoveAttributeVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractSupportedAttributeVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/ErrorRefVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/EscalationRefVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/MessageRefVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/SignalRefVisitor.java, backend-diagram-converter/core/src/main/resources/META-INF/services/org.camunda.community.migration.converter.visitor.DomElementVisitor, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/CoverageTest.java, backend-diagram-converter/core/src/test/resources/message-example.-.Kopie.bpmn, backend-diagram-converter/core/src/test/resources/message-example.bpmn, backend-diagram-converter/webapp/src/main/resources/static/lib/property-info-plugin.js, backend-diagram-converter/webapp/src/main/resources/static/lib/user-interaction.js, backend-diagram-converter/webapp/src/test/java/org/camunda/community/migration/converter/webapp/ConverterControllerTest.java, backend-diagram-converter/webapp/src/test/resources/application.yaml
Currently, every element is handled "standalone", meaning there is no relation between them displayed in the check results.
This leads to "invisible" messages for events ("bpmn:message", ...) as they are not part of the process diectly, but they are referenced from other elements.
This PR provides additional context to resolve this.
The messages will stay where they belong, but there will be 2-way references between elements.
For displaying the result, this means that any message from any referenced element will be shown on the element referring to it.
Closes #131 
There is a new unit test in placce that asserts the reference is defined correctly.
=> Feature: Event references

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/MessageFactory.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractListenerVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/ExecutionListenerVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/TaskListenerVisitor.java, backend-diagram-converter/core/src/main/resources/message-templates.properties, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/message/MessageFactoryTest.java, backend-diagram-converter/core/src/test/resources/execution-listener.bpmn, backend-diagram-converter/core/src/test/resources/user-task-listener-implementations.bpmn
The execution listener now has also a meaningful message
Closes #135 
There is a unit test in place
=> Reframed execution listener message

backend-diagram-converter/webapp/README.md, backend-diagram-converter/webapp/src/main/java/org/camunda/community/migration/converter/webapp/ConverterController.java, backend-diagram-converter/webapp/src/main/resources/static/index.html, backend-diagram-converter/webapp/src/main/resources/static/lib/user-interaction.js, backend-diagram-converter/webapp/src/test/java/org/camunda/community/migration/converter/webapp/ConverterControllerTest.java
For some time, the webapp was able to handle a multi-file upload. The current story does not align with this any more.
So, single file upload is back!
Closes #78 
Closes #142 
Closes #95 
The Integration tests for the REST API were adjusted to test the behaviour.
=> Feature: Webapp can only handle single-file uploads

camunda-7-adapter/src/main/java/org/camunda/community/migration/adapter/worker/CamundaPlatform7DelegationWorker.java, camunda-7-adapter/src/test/java/org/camunda/community/migration/adapter/CamundaPlatform7AdapterTest.java, camunda-7-adapter/src/test/java/org/camunda/community/migration/adapter/ErrorThrowingDelegate.java, camunda-7-adapter/src/test/resources/test-with-error-event.bpmn
Currently, the camunda-7-adapter is not able to handle BpmnErrors thrown by the JavaDelegate implementations.
As this is a default feature for Camunda 7, we need to support it.
There is a new test for the adapter that asserts the error handling by an error thrown from inside a JavaDelegate implementation.
=> Feature: Catch BpmnError in adapter and handle as ZeebeBpmnError

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformer.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/ExpressionTransformerTest.java
The empty keyword could not be handled correctly until now.
Closes #152 
There were added new test cases for the expression transformer.
=> [converter/core] bugfix: expression transformer now handles empty

backend-diagram-converter/core/src/main/resources/message-templates.properties
In Camunda 8 the business key isn't a separated entity anymore. It should be treated as a normal process variable.
For migration from Camunda 7 it would be fine just to keep the name `businessKey`.
The new message is the first and simple step for this issue: #197 
More changes should follow. We can inspect the context better.
The current message `BusinessKey is not supported by Zeebe` is correct, but misleading.
Manual tests.
=> Change Business key message

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformer.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/ExpressionTransformerTest.java, backend-diagram-converter/core/src/test/resources/empty-input-parameter.bpmn
The expression transformer did interpret an empty string as expression and mapped it to an empty expression.
In fact, it makes more sense to map it to a null expression.
Closes #198 
There is a unit test for the expression itself as well as a converter test to assert the correct message.
=> [converter/core] bugfix: Empty expression was transformed to '='

backend-diagram-converter/cli/pom.xml, pom.xml
With the release of the parent in version 1.4.2, there was the hope that we could now remove our added pom.xml configs to append build information to the manifest files.
This is not the case, however we can remove one thing.
Follow up to #221 
There is a unit test in place that starts an app which relies on a manifest entry.
=> [general] task: Remove not required pom.xml entries

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformer.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/ExpressionTransformerTest.java
JUEL allows the usage of single quotes for strings. They will be replaced with double quotes now
closes #272
closes #275 
There is an additional expression test in place
=> replace single quotes with double quotes

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/conversion/ErrorConversion.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/eventReference/ErrorVisitor.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java, backend-diagram-converter/core/src/test/resources/null-error-code.bpmn
In Camunda 7, it is ok to leave out the error code in a error to create a catch-all error.
This could not be converted as it lead to a null-pointer exception.
closes #315 
There is a new test added asserting the correct behaviour.
=> [bugfix][converter/core]: Empty error code leads to conversion error

backend-diagram-converter/cli/README.md, backend-diagram-converter/cli/src/main/java/org/camunda/community/migration/converter/cli/AbstractConvertCommand.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnConverter.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/ConverterProperties.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/ConverterPropertiesFactory.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/DefaultConverterProperties.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/MessageFactory.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractDelegateImplementationVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractSupportedAttributeVisitor.java, backend-diagram-converter/core/src/main/resources/converter-properties.properties, backend-diagram-converter/core/src/main/resources/message-templates.properties, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BehaviourTest.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/ConverterPropertiesTest.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/TestUtil.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/message/MessageFactoryTest.java, backend-diagram-converter/core/src/test/resources/delegate.bpmn, backend-diagram-converter/webapp/README.md, backend-diagram-converter/webapp/src/main/java/org/camunda/community/migration/converter/webapp/BpmnConverterService.java, backend-diagram-converter/webapp/src/main/java/org/camunda/community/migration/converter/webapp/ConverterController.java, backend-diagram-converter/webapp/src/main/resources/static/index.html, backend-diagram-converter/webapp/src/main/resources/static/lib/user-interaction.js, backend-diagram-converter/webapp/src/test/java/org/camunda/community/migration/converter/webapp/ConverterControllerTest.java
Currently, the converter assumes that the adapter is used afterwards to execute the service tasks being implemented with gateways before.
This new feature allows to not automatically define a job type.
closes #264 
There are tests in place that assert the positive and negative flag behaviour
=> [feature][converter/cli]: `defaultJobTypeEnabled` as flag

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/MessageFactory.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractTimerExpressionVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/CompletionConditionVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/ConditionExpressionVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/activity/CallActivityVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/AssigneeVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/CandidateGroupsVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/CandidateUsersVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/CollectionVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/DecisionRefVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/DueDateVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/FollowUpDateVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/ResourceVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/UserTaskFormRefVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/InOutVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/InputOutputParameterVisitor.java, backend-diagram-converter/core/src/main/resources/message-templates.properties, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/message/MessageFactoryTest.java, backend-diagram-converter/core/src/test/resources/conditional-flow-many-languages.bpmn
Although uncommon, it is possible to define a condition expression as script and even externalize this script.
The converter did not respect this until now.
closes #319 
There is a new test in place to assert the conversion behaviour on the different implementation types as well as tests for the new messages
=> bugfix: [converter/core] Differentiate between condition expression implementations

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/activity/BusinessRuleTaskVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/ResultVariableVisitor.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java, backend-diagram-converter/core/src/test/resources/business-rule-task-as-expression.bpmn
Mapping the result variable of a task was until now only depending on whether the task itself is a business rule task.
This worked in all cases except when a business rule task is implemented as expression with result variable.
In this case, it is treated as service task which leads to a problem with the convertible type.
The bug came in as notification from the hosted instance.
There is a new test in place to assert that this constellation is now covered properly
=> fix(converter/core): A business rule using an expression with result variable threw exception

backend-diagram-converter/core/src/main/resources/converter-properties.properties, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
=> Changed header name from scriptFormat to language

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformer.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/eventReference/EscalationVisitor.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java, backend-diagram-converter/core/src/test/resources/escalation-code.bpmn
This PR adds a null check before entering the expression transformation result
Issue appeared in hosted version
A test has been added to prove that the converter can handle a null escalation code
=> fix: handle null escalation code

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/activity/BusinessRuleTaskVisitor.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java, backend-diagram-converter/core/src/test/resources/default-result-variable.bpmn
=> fix: use default result variable in dmn

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/gateway/InclusiveGatewayVisitor.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
=> fix: inclusive gateway is fully supported in 8.6

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformationResult.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformer.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/CompletionConditionVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/ConditionExpressionVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/CollectionVisitor.java, backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/InputOutputParameterVisitor.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java, backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/ExpressionTransformerTest.java, backend-diagram-converter/core/src/test/resources/expression-get-variable.bpmn
resolves #1080 
Many users have written`${execution.getvariable("myVar") == "something"}`to avoid PropertyNotFoundException and compare with `null`, if the variables doesn't exist.
The current converter prints a warning `execution does not exists in FEEL`.
This change converts the JUEL expression into a valid FEEL expression `myVar = "something"`. null handling is done by FEEL nowadays.  
Junit tests added/adjusted.
=> Convert execution.getVariable("a") to a valid FEEL expression
