camunda-community-hub/camunda-7-to-8-migration

backend-diagram-converter/core/pom.xml
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/AbstractFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/BpmnConverterFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/ConversionFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/DomElementVisitorFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/element/InOutVisitor.java
backend-diagram-converter/core/src/test/java/org/camunda/community/converter/BehaviourTest.java
backend-diagram-converter/core/src/test/java/org/camunda/community/converter/BpmnModelInstanceUtil.java
backend-diagram-converter/core/src/test/java/org/camunda/community/converter/TestUtil.java
backend-diagram-converter/core/src/test/resources/behaviour/call-activity.bpmn
pom.xml

In the previous version, the call activity behaviour was explained wrong. Now, it is explained correctly and proved with a Unit test.
There is a test in place that transforms a process diagram from c7 to c8 and asserts the desired variable propagation behaviour

Fixed a bug where call activity behaviour was explained wrong

---

backend-diagram-converter/webapp/src/main/resources/static/index.html

This PR adds a legal disclaimer to the webapp. This might be a requirement as the webapp is available as service.
Robert Emsbach made me aware of this and I checked it with legal
No changes to actual functionality, so no tests

Added a legal disclaimer

---

backend-diagram-converter/cli/src/main/java/org/camunda/community/converter/cli/PrintNotificationServiceImpl.java
backend-diagram-converter/cli/src/main/resources/META-INF/services/org.camunda.community.converter.NotificationService
backend-diagram-converter/cli/src/main/resources/logback.xml
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/AbstractFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/BpmnConverter.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/BpmnConverterFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/BpmnDiagramCheckResult.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/DomElementVisitorContext.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/NotificationService.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/NotificationServiceFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/AbstractFilteringVisitor.java
backend-diagram-converter/core/src/main/resources/META-INF/services/org.camunda.community.converter.NotificationService
backend-diagram-converter/core/src/test/java/org/camunda/community/converter/BpmnConverterTest.java
backend-diagram-converter/webapp/README.md
backend-diagram-converter/webapp/src/main/java/org/camunda/community/converter/webapp/BpmnConverterService.java
backend-diagram-converter/webapp/src/main/java/org/camunda/community/converter/webapp/ConverterApplication.java
backend-diagram-converter/webapp/src/main/java/org/camunda/community/converter/webapp/ConverterController.java
backend-diagram-converter/webapp/src/main/java/org/camunda/community/converter/webapp/NotificationServiceImpl.java
backend-diagram-converter/webapp/src/main/resources/static/index.html

closes #53 
The webapp should be able to handle multiple files at once. This PR enables this
see #53 
The changes were tested in a test setup (no unit tests).
Stability of the core implementation is still existing due to other unit tests

Webapp: Allow multi-file upload

---

backend-diagram-converter/cli/pom.xml
backend-diagram-converter/cli/src/main/java/org/camunda/community/converter/cli/ConvertCommand.java
backend-diagram-converter/cli/src/main/java/org/camunda/community/converter/cli/MavenVersionProvider.java
backend-diagram-converter/cli/src/test/java/org/camunda/community/converter/cli/ConvertCommandTest.java
backend-diagram-converter/cli/src/test/resources/c7.bpmn
backend-diagram-converter/cli/src/test/resources/c8.bpmn

Until now, no version was displayed when using `-V` on the CLI tool 
Closes #75 
There is no test in place.

Converter CLI: Version displays maven project version

---

backend-diagram-converter/webapp/src/main/resources/static/index.html

The current disclaimer does not mention the notifications about technical problems. This has to be fixed.
The legal disclaimer is required as we are running this app publicly.
Closes #73 
No tests as this is not a technical issue.

Feature: Enhanced disclaimer

---

backend-diagram-converter/cli/src/test/java/org/camunda/community/converter/cli/ConvertCommandTest.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/ExpressionUtil.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/expression/ExpressionTransformationResult.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/expression/ExpressionTransformer.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/CompletionConditionVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/ConditionExpressionVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/activity/CallActivityVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/attribute/AssigneeVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/attribute/CandidateGroupsVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/attribute/CollectionVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/attribute/DecisionRefVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/attribute/UserTaskFormRefVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/element/InOutVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/element/InputOutputParameterVisitor.java
backend-diagram-converter/core/src/test/java/org/camunda/community/converter/ExpressionTransformerTest.java
backend-diagram-converter/core/src/test/java/org/camunda/community/converter/ExpressionUtilTest.java

closes #60 
The JUEL converter that was part of the Camunda Modeler Plugin was more advanced than the one that was embedded in Java.
I took both of them and created an immortal beast.
When converting diagrams, it might be required to transform expressions.
Of course, they are always subject to review, but the more we can handle, the better.
There is an extensive unit test for many different juel expressions that are transformed to become feel expressions.

feat (converter/core): Enhanced JUEL converter

---

backend-diagram-converter/cli/src/main/java/org/camunda/community/converter/cli/ConvertLocalCommand.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/BpmnElementFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/MessageAppender.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/conversion/AbstractTypedConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/conversion/ActivityConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/conversion/BusinessRuleTaskConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/conversion/CallActivityConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/conversion/DataMapperConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/conversion/FlownodeConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/conversion/MessageConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/conversion/SequenceFlowConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/conversion/ServiceTaskConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/conversion/UserTaskConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/DefinitionsVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/eventDefinition/TerminateEventDefinitionVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/converter/visitor/impl/gateway/InclusiveGatewayVisitor.java
backend-diagram-converter/core/src/main/resources/META-INF/services/org.camunda.community.converter.visitor.DomElementVisitor
backend-diagram-converter/core/src/test/java/org/camunda/community/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/resources/old-process.bpmn20.xml

Right now, the order of elements might be wrong. This bugfix resolves one finding.
Closes #112 
The model causing the problem was added to the list of tested models

Bugfix: The converter respects the order of elements

---

README.md
camunda-7-adapter/readme.md

Adjusted docs

---

.github/workflows/build.yaml
.github/workflows/main.yml
example/process-solution-camunda-7/pom.xml
example/process-solution-camunda-7/src/main/java/org/camunda/community/migration/example/Application.java
example/process-solution-camunda-7/src/main/resources/process.bpmn
example/process-solution-camunda-7/src/test/java/org/camunda/community/migration/example/ApplicationTest.java
example/process-solution-migrated/pom.xml
example/process-solution-migrated/src/main/java/org/camunda/community/migration/example/Application.java
example/process-solution-migrated/src/test/java/org/camunda/community/migration/example/ApplicationTest.java

Since the last cleaning, the example projects are fixed, but not independent on the rest any more.
This was changed.
Closes #126 
There are now tests in place that verify the examples are still working.

Task: Make example Projects standalone

---

backend-diagram-converter/core/src/main/resources/message-templates.properties

Keep the messages consistent
input output mappings: all parameters should be quoted.
no tests written

highlight the mapped parameter with quotes

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnDiagramCheckResult.java
backend-diagram-converter/core/src/main/resources/message-templates.properties
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/webapp/src/main/resources/static/lib/user-interaction.js
backend-diagram-converter/webapp/src/main/resources/static/styles/viewer.css

Some elements can not be converted and require a WARNING output. Some elements can be converted, but need special attention on the conversion result, for example messages with their `correlation-key`
This pull request introduced a new severity level `REVIEW`. It is used for all conversions, that should be double-checked (Mostly feel expressions).
The severity `TASK` will be highlighted on the same level as `WARNING` in orange, as the severity `REVIEW` will be blue.
fixes #133 
Given JUnit tests are changed to the new severity.
Diagram markup is tested manually.

Add new severity REVIEW between TASK and INFO.

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/MessageFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/ConditionExpressionVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/gateway/ComplexGatewayVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/gateway/ExclusiveGatewayVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/gateway/InclusiveGatewayVisitor.java
backend-diagram-converter/core/src/main/resources/message-templates.properties
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/resources/conditional-flow.bpmn

Zeebe does not support Conditional Flows atm.
This bugfix provides a logic, a message and a test that asserts the required behaviour.
There is a unit test that asserts the behaviour

Bugfix: A conditional flow was not recognized

---

camunda-7-adapter/src/main/java/org/camunda/community/migration/adapter/worker/CamundaPlatform7DelegationWorker.java
camunda-7-adapter/src/test/java/org/camunda/community/migration/adapter/ErrorThrowingDelegate.java

Bugfix: BpmnError without message was not handled correctly

---

backend-diagram-converter/cli/src/main/java/org/camunda/community/migration/converter/cli/AbstractConvertCommand.java

fixes #172 
output tested manually

Add output when csv write was successful

---

README.md
backend-diagram-converter/cli/README.md
backend-diagram-converter/cli/pom.xml
backend-diagram-converter/cli/src/main/java/org/camunda/community/migration/converter/cli/ConvertCommand.java
backend-diagram-converter/cli/src/main/java/org/camunda/community/migration/converter/cli/ConvertEngineCommand.java
backend-diagram-converter/cli/src/main/java/org/camunda/community/migration/converter/cli/ConvertLocalCommand.java

The README page of the CLI lists all available command and options. 
I've also refined some wording in the options and commands.
Maven now generates a jar with the artifact name, it is the same as available on maven central (`backend-diagram-converision-cli.jar`). The version is omitted on local builds. Most often it will be x.y.z-SNAPSHOT.
The help output in the terminal windows displays the name as `java -Dfile.encoding=UFT-8 -jar backend-diagram-converter-cli.jar` as this is the easiest way to invoke it after a download from Artifactory or Maven Central.
I made manual tests to check the console output.

Improve documentation about the CLI converter commands and options

---

backend-diagram-converter/webapp/src/main/resources/static/description.html
backend-diagram-converter/webapp/src/main/resources/static/index.html

Explain more details and streamline the user experince.
closes #184 
A user who is not familiar with the tool may not understand all details. They are explained now on a separate page. 
The styling may change.
just manually. Opening the pages in local browser.

Improve self-service

---

pom.xml

Eclipse is complaining about the maven-enforcer-plugin which is not covered in its internal life cycle.
A configuration on the root pom in pluginManagement helps with this issue.
@jonathanlukas, can you please check this on intelliJ?

Add eclipse support (ignore) for maven-enforcer-plugin

---

backend-diagram-converter/cli/pom.xml
backend-diagram-converter/webapp/pom.xml
backend-diagram-converter/webapp/src/main/java/org/camunda/community/migration/converter/webapp/ConverterController.java
backend-diagram-converter/webapp/src/main/resources/static/description.html
backend-diagram-converter/webapp/src/main/resources/static/index.html
backend-diagram-converter/webapp/src/main/resources/static/lib/property-info-plugin.js
backend-diagram-converter/webapp/src/main/resources/static/lib/user-interaction.js

Now you can see on the web page, which version of the converter is used.
To access the version info from maven in the source code, two different approaches are required.
`this.getClass().getPackage().getImplementationVersion()` for java programs 
and 
`buildProperties.getVersion()` for spring boot.
Both require special settings in the pom.xml:
* https://stackoverflow.com/a/43383222
* https://stackoverflow.com/a/65236252.
I used this branch to correct the description page as well.
It resolves #193 
Tested manually.

[converter/webapp] feature: Publish version of the server and show it

---

README.md
backend-diagram-converter/README.md
backend-diagram-converter/cli/README.md
backend-diagram-converter/webapp/README.md
camunda-7-adapter/readme.md
modeler-plugin-7-to-8-converter/readme.md
process-instance-migration/README.md

Reformat the README files.
Add a hint to the modeler plugin README that this module is currently not maintained and the diagram converter should be used instead.
resolves #218

[task] Reformat markdown prose files with prettier

---

pom.xml

Until now, the Spring Zeebe Starter pointed to the wrong version ref.
Just the existing tests

Updated Spring Zeebe Starter version ref

---

camunda-7-adapter/pom.xml

Removed a build plugin that was required back when the project was no multi-module
Solves nothing, but prevents potential inconsitences
No testing required

Removed redundant build plugin

---

README.md
migration-approaches/Curated-List.md

Started building a curated list of interesting approaches which should help to during migration.
List of interesting approaches which should help to migrate. It might be an architectural approach or just tips and tricks / experiences to keep in mind.

added curated list of community migration approaches

---

migration-approaches/Curated-List.md

Starting a list of migration approaches, VanillaBP should be part of this list as well.
Add VanillaBP to the list of curated migration approaches.
It's worth to share the recording from the Camunda Community Summit talk.

Add VanillaBP to curated list.

---

README.md

fixed link after renaming of markdown file

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnConverter.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnDiagramCheckResult.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/DefinitionsVisitor.java

The converter will start exporting its own version in the results.
closes #223 
Testing this is not easy as the package version is only available on built artefacts

feature: [converter/core] Export converter version

---

cawemo-to-web-modeler-migration/migrate-cawemo-to-web-modeler.sh

Makes the migration script call Web Modeler's `v1` API instead of `beta`
Relates to https://github.com/camunda/web-modeler/issues/6063
* Manual testing against Cawemo and Web Modeler SaaS
* There is no API for Cawemo to create new files, hence automated tests can't be written

chore: [cawemo-migration] Switch to api v1

---

pom.xml

closes #438 
Tested with docker images

Added a default language and charset

---

.github/dependabot.yml

Dependabot: removed custom labels

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/MessageTemplateProcessor.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/message/MessageTemplateProcessorTest.java

There was an error in the replacement when weird stuff like `\\$$` was part of the scene.
This is now fixed.
The diagram converter reported an issue on 2023-12-20 4pm GMT
There is a new test in place to assert that the replacement is working and the results are expected.

Improved quote replacement to prevent errors

---

process-instance-migration/pom.xml
process-instance-migration/src/test/java/org/camunda/community/migration/processInstance/ScenarioTestSuite.java
process-instance-migration/src/test/resources/bpmn/c7/multi-instance-subprocess.bpmn
process-instance-migration/src/test/resources/bpmn/c8/parallel-fork-join.bpmn
process-instance-migration/src/test/resources/bpmn/c8/subprocess.bpmn
process-instance-migration/src/test/resources/bpmn/c8/user-tasks-linear.bpmn
process-instance-migration/src/test/resources/bpmn/c8/user-tasks-parallel.bpmn

updated to latest node version

---

process-instance-migration/src/main/frontend/package-lock.json

Reverts camunda-community-hub/camunda-7-to-8-migration#673

Revert "fix(deps): update dependency vue to v3.4.7"

---

backend-diagram-converter/core/src/main/resources/converter-properties.properties

Make 8.4 default version

---

.github/workflows/build.yaml
.github/workflows/main.yml
.gitignore
cawemo-to-web-modeler-migration/README.md
cawemo-to-web-modeler-migration/cawemo-to-web-modeler-migration.go
cawemo-to-web-modeler-migration/go.mod
cawemo-to-web-modeler-migration/setup.sh

The current implementation of the migration script has some weaknesses. The go script does overcome them (or at least some).

Cawemo to Web Modeler Migration with go script

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractAttributeVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractBpmnAttributeVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractCamundaAttributeVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractEventRefVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/MessageRefVisitor.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/resources/message-event-definition-handling.bpmn

In Camunda 7, send events could have a message ref. This did not have any effect, but was conform to BPMN standards.
Camunda 8 does not make use of this verbose declaration at all, this is why these refs need to be removed on conversion.
There is a test in place to assert that only intermediateThrowEvents and endEvents have the messageRef removed from the message event definition.

Bugfix: message ref on send events

---

code-migration-detector/README.md

The template for the `MigrationPreparationTest` doesn't test everything.
I had to do some manual corrections to run the `MigrationPreparationTest`for the first time.
I copied the template in my migration example project and run it with `mvn test` to get the desired result. I violated the **No Task Listener Rule**

Correct template for MigrationPreparationTest

---

README.md

Add code migration detector to readme

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/conversion/UserTaskConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/convertible/UserTaskConvertible.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/version/SemanticVersion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/IsForCompensationVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/activity/UserTaskVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/eventDefinition/CompensateEventDefinitionVisitor.java
backend-diagram-converter/core/src/main/resources/converter-properties.properties
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnElementSupportTest.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/TestUtil.java

Prepare 8.5

---

backend-diagram-converter/webapp/src/main/java/org/camunda/community/migration/converter/webapp/NotificationServiceImpl.java

replaced deprecated files upload api

---

backend-diagram-converter/core/README.md
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/ConverterPropertiesFactory.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/ConverterPropertiesTest.java
example/extended-converter/pom.xml
example/extended-converter/src/main/java/org/camunda/community/migration/example/extendedConverter/CustomDomElementVisitor.java
example/extended-converter/src/main/resources/META-INF/services/org.camunda.community.migration.converter.visitor.DomElementVisitor
example/extended-converter/src/test/java/org/camunda/community/migration/example/extendedConverter/ExtendedConverterTest.java
example/extended-converter/src/test/resources/example-model.bpmn
example/pom.xml
example/sample-external-task-process-app-migrated/src/test/java/org/camunda/community/migration_example/ApplicationTest.java

documented diagram converter core

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnConverter.java
camunda-7-adapter/pom.xml
example/extended-converter/pom.xml
example/extended-converter/src/main/java/org/camunda/community/migration/example/extendedConverter/TaskTopicVisitor.java
example/extended-converter/src/main/resources/META-INF/services/org.camunda.community.migration.converter.visitor.DomElementVisitor
example/extended-converter/src/test/java/org/camunda/community/migration/example/extendedConverter/ExtendedConverterTest.java
example/extended-converter/src/test/resources/ExternalTaskWorker_Example.bpmn
pom.xml
process-instance-migration/pom.xml

added another example about converter extension

---

backend-diagram-converter/cli/src/main/java/org/camunda/community/migration/converter/cli/AbstractConvertCommand.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnConverter.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/ConverterProperties.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/ConverterPropertiesFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/DefaultConverterProperties.java
backend-diagram-converter/core/src/main/resources/converter-properties.properties
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/TestUtil.java
backend-diagram-converter/core/src/test/resources/history-time-to-live.bpmn

feat: omit conversion messages in bpmn xml

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractListenerVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/ExecutionListenerVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/TaskListenerVisitor.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/resources/delegate-expression-listener.bpmn

feat: remove brackets on delegate expression listener

---

backend-diagram-converter/core/src/main/resources/message-templates.properties

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208809776214594

fix: append more useful information to the message

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/convertible/AbstractGatewayConvertible.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/resources/gateway-with-el.bpmn

fix: a gateway can have execution listeners

---

backend-diagram-converter/cli/src/main/java/org/camunda/community/migration/converter/cli/AbstractConvertCommand.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/ConverterProperties.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/ConverterPropertiesFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/DefaultConverterProperties.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/conversion/ServiceTaskConversion.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/MessageFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractDelegateImplementationVisitor.java
backend-diagram-converter/core/src/main/resources/converter-properties.properties
backend-diagram-converter/core/src/main/resources/message-templates.properties
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/message/MessageFactoryTest.java

feat: use delegate expression as job type

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/MessageFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/InputOutputParameterVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/ScriptVisitor.java
backend-diagram-converter/core/src/main/resources/message-templates.properties
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/message/MessageFactoryTest.java
backend-diagram-converter/core/src/test/resources/feel_expr_not_tranformed.bpmn

fix: transform feel script in output and output

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/MessageFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractListenerVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/ExecutionListenerVisitor.java
backend-diagram-converter/core/src/main/resources/message-templates.properties
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/message/MessageFactoryTest.java
backend-diagram-converter/core/src/test/resources/take-listener.bpmn

fix: take listener are not respected

---

camunda-7-adapter/readme.md

remove execution listener workaround in adapter

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnConverter.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/BpmnDiagramCheckResult.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/DomElementVisitorContext.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/ComposedMessage.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/EmptyMessage.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/Message.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/MessageFactory.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/CsvWriterTest.java

the csv and json export will contain an id for each message

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/conversion/UserTaskConversion.java

fix: a zeebe user task has an external form reference

---

backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/convertible/AbstractDataMapperConvertible.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformationResult.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformationResultMessageFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformer.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/message/MessageFactory.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/AbstractTimerExpressionVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/CompletionConditionVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/ConditionExpressionVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/activity/CallActivityVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/AssigneeVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/CandidateGroupsVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/CandidateUsersVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/CollectionVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/DecisionRefVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/DueDateVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/FollowUpDateVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/attribute/UserTaskFormRefVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/InOutVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/element/InputOutputParameterVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/eventReference/ErrorVisitor.java
backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/visitor/impl/eventReference/EscalationVisitor.java
backend-diagram-converter/core/src/main/resources/message-templates.properties
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/BpmnConverterTest.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/ExpressionTransformerTest.java
backend-diagram-converter/core/src/test/java/org/camunda/community/migration/converter/message/MessageFactoryTest.java

feat: unified way of transforming an expression to the according message

---

example/process-solution-camunda-7/pom.xml
example/process-solution-camunda-7/src/test/resources/application.yaml
example/process-solution-migrated/pom.xml
example/process-solution-migrated/src/test/java/org/camunda/community/migration/example/ApplicationTest.java
example/sample-external-task-process-app-migrated/pom.xml
example/sample-external-task-process-app-migrated/src/test/java/org/camunda/community/migration_example/ApplicationTest.java
example/sample-external-task-process-app/pom.xml

upgrade examples to 8.7
